### ISSUE TITLE
get_option_chains, no_of_strikes parameter does not work with int or string

### ISSUE THREAD

**Issue by patter001** [jessecooper/pyetrade#27]

**Comment by patter001** [comment]
Fixed with #26

**Comment by jessecooper** [comment]
Thank you for the PR

**Comment by happyshows** [comment]
@jessecooper   there seem to be a regression, still seeing the error

![image](https://user-images.githubusercontent.com/3208181/98430433-b7fb6a80-2072-11eb-8126-28da8163e7e4.png)
